---
nyc:
  all: true
  check-coverage: true
  extension:
    - ".js"
  include:
    - src/js/**/*.js
    - src/js/**/*.spec.mocha.js
  exclude:
    - config
    - node_modules
  reporter:
    - html
    - text
  watermarks:
    lines:
      - 80
    functions:
      - 80
    branches:
      - 80
    statements:
      - 80
