---
env:
  browser: true
  es6: true
  node: true
extends:
  - plugin:prettier/recommended
plugins:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  prettier/prettier: error
