# This is an example Mocha config containing every Mocha option plus others
allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
exit: false # could be expressed as "no-exit: true"
extension:
  - js
forbid-only: false
forbid-pending: false
full-trace: false
global:
  - jQuery
  - $
growl: false
inline-diffs: false
recursive: false
reporter: spec
retries: 1
slow: 75
sort: false
spec: src/js/**/*.spec.mocha.js
timeout: false
trace-warnings: true
ui: bdd
watch: true
watch-files:
 - src/js/**/*.js
