---
env:
  browser: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - prettier
  - '@typescript-eslint'
extends:
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  prettier/prettier: error
